languageCode = "en-gb"
title = "A+ Accessibility and Inclusive Design Audit"
baseURL = "https://apluslms.github.io/accessibility-audit/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "The A+ accessibility and inclusive design audit report."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true